export const quiz4 =  {
  "quizTitle": "Section 4: Exotics",
  "quizSynopsis": "This is the last part - but also the hardest. Get ready.",

  "appLocale": {
    "landingHeaderText": "<questionLength> Exotic Perks",
    "question": "Perk",
    "startQuizBtn": "Let's do it.",
    "resultFilterAll": "All",
    "resultFilterCorrect": "Correct",
    "resultFilterIncorrect": "Incorrect",
    "nextQuestionBtn": "Next",
    "resultPageHeaderText": "You have completed this section. You got <correctIndexLength> out of <questionLength> questions.",
    "singleSelectionTagText": "Section 4",
    "pickNumberOfSelection": "Choose <numberOfSelection>",
  },

  "questions": [
    {
      "question": "Which exotic weapon does this perk belong to?",
      "questionType": "photo",
      "questionPic": "https://d2.destinygamewiki.com/mediawiki/images/b/bf/Vermin_icon.png",
      "answers": [
        "https://d2.destinygamewiki.com/mediawiki/images/7/7a/Two-tailed_fox_icon1.jpg",
        "https://d2.destinygamewiki.com/mediawiki/images/archive/c/c9/20190929154649%21Tarrabah_icon1.jpg",
        "https://d2.destinygamewiki.com/mediawiki/images/3/3e/Fighting_lion_icon1.png",
        "https://d2.destinygamewiki.com/mediawiki/images/9/91/Rat_king_icon1.png"
      ],
      "correctAnswer": "4",
      "messageForCorrectAnswer": "This is only here to satisfy a certain madman - you know who you are.",
      "messageForIncorrectAnswer": "Rat King is a quest exotic that must be earned with a fireteam.",
      "explanation": "Rat King - Vermin: Reloading immediately after a kill grants a brief period of invisibility.",
      "segment": "Easy",
      "segment2": "5 Points",
      "point": "5",
    },
    {
      "question": "Which exotic weapon does this perk belong to?",
      "questionType": "photo",
      "questionPic": "https://d2.destinygamewiki.com/mediawiki/images/1/1b/Memento_Mori_icon.png",
      "answers": [
        "https://d2.destinygamewiki.com/mediawiki/images/7/72/Monte_carlo_icon1.jpg",
        "https://d2.destinygamewiki.com/mediawiki/images/5/5f/IMG_8812.JPG",
        "https://d2.destinygamewiki.com/mediawiki/images/c/c6/The_last_word_icon1.jpg",
        "https://d2.destinygamewiki.com/mediawiki/images/1/1a/Truth_icon1.jpg"
      ],
      "correctAnswer": "2",
      "messageForCorrectAnswer": "'I'm comin' home, Ace.'",
      "messageForIncorrectAnswer": "'I'm comin' home, Ace.'",
      "explanation": "Ace of Spades - Memento Mori: Reloading after a kill loads magazine with a few extra-damage bullets. Grants radar while aiming down sights.",
      "segment": "Easy",
      "segment2": "5 Points",
      "point": "5",
    },
    {
      "question": "Which exotic weapon does this perk belong to?",
      "questionType": "photo",
      "questionPic": "https://d2.destinygamewiki.com/mediawiki/images/2/2a/Disease_Vector_icon.png",
      "answers": [
        "https://d2.destinygamewiki.com/mediawiki/images/0/00/Sleeper_Simulant_icon1.jpg",
        "https://d2.destinygamewiki.com/mediawiki/images/e/e1/Hard_light_icon1.png",
        "https://d2.destinygamewiki.com/mediawiki/images/c/cf/Outbreak_perfected_icon1.jpg",
        "https://d2.destinygamewiki.com/mediawiki/images/a/aa/Darci_icon1.png"
      ],
      "correctAnswer": "3",
      "messageForCorrectAnswer": "~directive = KILL while enemies = PRESENT: execute(directive)~",
      "messageForIncorrectAnswer": "A secret exotic - Outbreak Perfected. Originally known as Outbreak Prime, from D1.",
      "explanation": "Outbreak Perfected - Disease Vector: Increases nanite damage. Enemies that die with nanites attached to them generate additional nanites.",
      "segment": "Easy",
      "segment2": "5 Points",
      "point": "5",
    },
    {
      "question": "Which exotic weapon does this perk belong to?",
      "questionType": "photo",
      "questionPic": "https://d2.destinygamewiki.com/mediawiki/images/d/db/Poison_arrows_icon1.png",
      "answers": [
        "https://d2.destinygamewiki.com/mediawiki/images/4/45/Wish-ender_icon1.jpg",
        "https://d2.destinygamewiki.com/mediawiki/images/c/c4/Black_talon_icon1.jpg",
        "https://d2.destinygamewiki.com/mediawiki/images/2/27/IMG_8810.JPG",
        "https://d2.destinygamewiki.com/mediawiki/images/d/d9/Le_monarque_icon1.jpg"
      ],
      "correctAnswer": "4",
      "messageForCorrectAnswer": "One of my personal favourites - Le Monarque. Can we get a catalyst pls Bungo thx",
      "messageForIncorrectAnswer": "A Black Armory exotic, and one of my personal favourites - Le Monarque.",
      "explanation": "Le Monarque - Poison Arrows: Arrows fired quickly after a full draw become poison arrows. Precision hits with poison arrows spread poison to nearby enemies.",
      "segment": "Easy",
      "segment2": "5 Points",
      "point": "5",
    },
    {
      "question": "Which exotic weapon does this perk belong to?",
      "questionType": "photo",
      "questionPic": "https://d2.destinygamewiki.com/mediawiki/images/d/d8/Looks_can_kill_icon1.png",
      "answers": [
        "https://d2.destinygamewiki.com/mediawiki/images/b/b5/Izanagi%27s_burden_icon1.jpg",
        "https://d2.destinygamewiki.com/mediawiki/images/4/42/Jade_rabbit_osiris_icon1.png",
        "https://d2.destinygamewiki.com/mediawiki/images/a/ad/Eriana%27s_vow_icon1.jpg",
        "https://d2.destinygamewiki.com/mediawiki/images/3/3e/Fighting_lion_icon1.png"
      ],
      "correctAnswer": "3",
      "messageForCorrectAnswer": "Comes with built in anti-barrier! Pretty handy.",
      "messageForIncorrectAnswer": "The only 'Hand Cannon/Sniper Hybrid' in the game. Does a LOT of damage on crits.",
      "explanation": "Eriana's Vow - Looks Can Kill: This weapon fires special shield-piercing ammunition. It comes with a scope.",
      "segment": "Easy",
      "segment2": "5 Points",
      "point": "5",
    },
    {
      "question": "Which exotic weapon does this perk belong to?",
      "questionType": "photo",
      "questionPic": "https://d2.destinygamewiki.com/mediawiki/images/d/d3/Accomplice_icon1.png",
      "answers": [
        "https://d2.destinygamewiki.com/mediawiki/images/3/3c/Sturm_icon1.png",
        "https://d2.destinygamewiki.com/mediawiki/images/9/9c/Vigilance_wing_icon1.png",
        "https://d2.destinygamewiki.com/mediawiki/images/1/11/Bastion_icon1.jpg",
        "https://d2.destinygamewiki.com/mediawiki/images/b/bd/Divinity_icon1.jpg"
      ],
      "correctAnswer": "1",
      "messageForCorrectAnswer": "So apparently this weapon blew up now that 120s are everywhere. We love 120s  :)",
      "messageForIncorrectAnswer": "Sturm is an exotic hand cannon designed to be paired with Drang, a legendary sidearm.",
      "explanation": "Sturm - Accomplice: Kills with this weapon fill the magazine of the equipped Energy weapon from reserves.",
      "segment": "Medium",
      "segment2": "10 Points",
      "point": "10",
    },
    {
      "question": "Which exotic weapon does this perk belong to?",
      "questionType": "photo",
      "questionPic": "https://d2.destinygamewiki.com/mediawiki/images/0/01/Big-game_hunter_icon1.png",
      "answers": [
        "https://d2.destinygamewiki.com/mediawiki/images/d/de/Cerberus1_icon1.jpg",
        "https://d2.destinygamewiki.com/mediawiki/images/3/3e/Fighting_lion_icon1.png",
        "https://d2.destinygamewiki.com/mediawiki/images/5/5e/The_fourth_horseman_icon1.jpg",
        "https://d2.destinygamewiki.com/mediawiki/images/e/e5/Leviathan%27s_breath_icon1.jpg"
      ],
      "correctAnswer": "4",
      "messageForCorrectAnswer": "Michael says this thing can out DPS Xenophage with Actium. Do we believe him?",
      "messageForIncorrectAnswer": "The only heavy bow in the game. Apparently, (according to Michael, so who knows) it's actually pretty good.",
      "explanation": "Leviathan's Breath - Big-Game Hunter: Fires a massive heavy bolt that staggers unshielded enemy combatants. Strong against Unstoppable Champions.",
      "segment": "Medium",
      "segment2": "10 Points",
      "point": "10",
    },
    {
      "question": "Which exotic weapon does this perk belong to?",
      "questionType": "photo",
      "questionPic": "https://d2.destinygamewiki.com/mediawiki/images/a/a0/Business_time_icon1.png",
      "answers": [
        "https://d2.destinygamewiki.com/mediawiki/images/2/22/Sweet_business_icon2.png",
        "https://d2.destinygamewiki.com/mediawiki/images/d/d1/Anarchy_icon1.jpg",
        "https://d2.destinygamewiki.com/mediawiki/images/9/9c/Sunshot_icon2.png",
        "https://d2.destinygamewiki.com/mediawiki/images/e/e5/Heir_apparent_icon1.jpg"
      ],
      "correctAnswer": "1",
      "messageForCorrectAnswer": "BRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRT.",
      "messageForIncorrectAnswer": "BRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRT.",
      "explanation": "Sweet Business - Business Time: Sustained fire boosts this weapon's range and rate of fire.",
      "segment": "Medium",
      "segment2": "10 Points",
      "point": "10",
    },
    {
      "question": "Which exotic weapon does this perk belong to?",
      "questionType": "photo",
      "questionPic": "https://d2.destinygamewiki.com/mediawiki/images/e/e2/Cold_fusion_icon1.png",
      "answers": [
        "https://d2.destinygamewiki.com/mediawiki/images/b/b3/Arbalest_icon1.jpg",
        "https://d2.destinygamewiki.com/mediawiki/images/archive/2/25/20200130235648%21Coldheart_icon1.png",
        "https://d2.destinygamewiki.com/mediawiki/images/c/c4/Prometheus_lens_icon1.png",
        "https://d2.destinygamewiki.com/mediawiki/images/1/1d/Skyburners_oath_icon1.png"
      ],
      "correctAnswer": "2",
      "messageForCorrectAnswer": "Year 1 veteran? The good old days of freezing Calus with Coldheart.",
      "messageForIncorrectAnswer": "Coldheart used to be the go-to for boss damage in Year 1. How times have changed.",
      "explanation": "Coldheart - Cold Fusion: This weapon shoots a steady cold fusion-powered laser.",
      "segment": "Medium",
      "segment2": "10 Points",
      "point": "10",
    },
    {
      "question": "Which exotic weapon does this perk belong to?",
      "questionType": "photo",
      "questionPic": "https://d2.destinygamewiki.com/mediawiki/images/d/d2/Mad_Scientist_icon.png",
      "answers": [
        "https://d2.destinygamewiki.com/mediawiki/images/e/e5/Heir_apparent_icon1.jpg",
        "https://d2.destinygamewiki.com/mediawiki/images/0/00/Sleeper_Simulant_icon1.jpg",
        "https://d2.destinygamewiki.com/mediawiki/images/b/bf/IMG_8808.JPG",
        "https://d2.destinygamewiki.com/mediawiki/images/0/0a/The_wardcliff_coil_icon1.png"
      ],
      "correctAnswer": "4",
      "messageForCorrectAnswer": "Eyes of Tomorrow = Wardcliff 2: Electric Boogaloo.",
      "messageForIncorrectAnswer": "I wonder if The Wardcliff Coil is better than Eyes of Tomorrow.",
      "explanation": "The Wardcliff Coil - Mad Scientist: This weapon fires a volley of rockets.",
      "segment": "Medium",
      "segment2": "10 Points",
      "point": "10",
    },
    {
      "question": "Which exotic weapon does this perk belong to?",
      "questionType": "photo",
      "questionPic": "https://d2.destinygamewiki.com/mediawiki/images/5/54/Sun_blast_icon1.png",
      "answers": [
        "https://d2.destinygamewiki.com/mediawiki/images/7/7b/Telesto_icon2.jpg",
        "https://d2.destinygamewiki.com/mediawiki/images/9/9c/Sunshot_icon2.png",
        "https://d2.destinygamewiki.com/mediawiki/images/7/70/Witherhoard_icon1.jpg",
        "https://d2.destinygamewiki.com/mediawiki/images/d/da/Graviton_lance_icon1.png"
      ],
      "correctAnswer": "2",
      "messageForCorrectAnswer": "For many of us, this was our very first exotic weapon. Do you remember those days?",
      "messageForIncorrectAnswer": "Sunshot was once given to players as part of the Red War campaign - but now, it's a random drop.",
      "explanation": "Sunshot - Sun Blast: Targets killed with Sunshot explode in Solar energy.",
      "segment": "Hard",
      "segment2": "20 Points",
      "point": "20",
    },
    {
      "question": "Which exotic weapon does this perk belong to?",
      "questionType": "photo",
      "questionPic": "https://d2.destinygamewiki.com/mediawiki/images/5/53/Superconductor_icon1.png",
      "answers": [
        "https://d2.destinygamewiki.com/mediawiki/images/6/6b/Ruinous_Effigy_icon.jpg",
        "https://d2.destinygamewiki.com/mediawiki/images/5/57/Riskrunner_icon1.png",
        "https://d2.destinygamewiki.com/mediawiki/images/b/bf/IMG_8808.JPG",
        "https://d2.destinygamewiki.com/mediawiki/images/d/df/Devil%27s_ruin_icon1.jpg"
      ],
      "correctAnswer": "2",
      "messageForCorrectAnswer": "Another OG Year 1 exotic. It still slaps, to this day.",
      "messageForIncorrectAnswer": "Same, wtf is that perk icon lmao",
      "explanation": "Riskrunner - Superconductor: When Arc Conductor is active, shots fired have the chance to become chain lightning and return ammo.",
      "segment": "Hard",
      "segment2": "20 Points",
      "point": "20",
    },
    {
      "question": "Which exotic weapon does this perk belong to?",
      "questionType": "photo",
      "questionPic": "https://d2.destinygamewiki.com/mediawiki/images/c/cf/Foaf_icon1.png",
      "answers": [
        "https://d2.destinygamewiki.com/mediawiki/images/1/10/MIDA_multi-tool_icon1.png",
        "https://d2.destinygamewiki.com/mediawiki/images/6/6d/Symmetry_icon1.jpg",
        "https://d2.destinygamewiki.com/mediawiki/images/1/1d/Skyburners_oath_icon1.png",
        "https://d2.destinygamewiki.com/mediawiki/images/4/42/Jade_rabbit_osiris_icon1.png"
      ],
      "correctAnswer": "4",
      "messageForCorrectAnswer": "Jade Rabbit > Dead Man's Tale     don't @ me",
      "messageForIncorrectAnswer": "Jade Rabbit > Dead Man's Tale     don't @ me",
      "explanation": "The Jade Rabbit - The Fate of All Fools: Chain body shots to gain bonus damage on your next precision shot and return ammo to the magazine.",
      "segment": "Hard",
      "segment2": "20 Points",
      "point": "20",
    },
    {
      "question": "Which exotic weapon does this perk belong to?",
      "questionType": "photo",
      "questionPic": "https://d2.destinygamewiki.com/mediawiki/images/1/10/Conserve_momentum_icon1.png",
      "answers": [
        "https://d2.destinygamewiki.com/mediawiki/images/1/17/Traveler%27s_chosen_icon1.jpg",
        "https://d2.destinygamewiki.com/mediawiki/images/6/6b/Ruinous_Effigy_icon.jpg",
        "https://d2.destinygamewiki.com/mediawiki/images/b/bd/Divinity_icon1.jpg",
        "https://d2.destinygamewiki.com/mediawiki/images/0/05/Merciless_icon1.png"
      ],
      "correctAnswer": "4",
      "messageForCorrectAnswer": "Lots of the old timers in this quiz - another OG Year 1 weapon.",
      "messageForIncorrectAnswer": "Nobody saw it coming. Believe it or not, this used to be the king of DPS a long time ago.",
      "explanation": "Merciless - Conserve Momentum: Non-lethal hits with projectiles make this weapon charge faster until its wielder gets a kill.",
      "segment": "Hard",
      "segment2": "20 Points",
      "point": "20",
    },
    {
      "question": "Which exotic weapon does this perk belong to?",
      "questionType": "photo",
      "questionPic": "https://d2.destinygamewiki.com/mediawiki/images/f/f2/Fan_fire_icon1.png",
      "answers": [
        "https://d2.destinygamewiki.com/mediawiki/images/c/c7/The_chaperone_icon1.jpg",
        "https://d2.destinygamewiki.com/mediawiki/images/c/c6/The_last_word_icon1.jpg",
        "https://d2.destinygamewiki.com/mediawiki/images/8/85/The_prospector_icon1.png",
        "https://d2.destinygamewiki.com/mediawiki/images/9/92/The_huckleberry_icon1.jpg"
      ],
      "correctAnswer": "2",
      "messageForCorrectAnswer": "You've yee'd your last haw - let's see how you did.",
      "messageForIncorrectAnswer": "You've yee'd your last haw - let's see how you did.",
      "explanation": "The Last Word - Fan Fire: This weapon can be fired quickly and continuously. Faster reload and increased accuracy on successive hip-fire damage.",
      "segment": "Hard",
      "segment2": "20 Points",
      "point": "20",
    },
  ]
}

export default quiz4;